-- Credential verification is defined in db/schema/02_users_and_auth.sql.
-- Apply that script after the core schema; there is no second function here.
-- The previous standalone definition had the same input signature but a
-- different return type, so applying both definitions was not a valid setup.
--
-- Existing databases: compare the installed function with the canonical
-- definition before migrating. PostgreSQL cannot change its return type with
-- CREATE OR REPLACE. Any required drop/recreate must be planned with its
-- dependencies, permissions, and application downtime in mind.
-- Do not drop the deployed function just to rerun bootstrap scripts.
